### ISSUE TITLE
Change to nonblock-statement-body-position

### ISSUE THREAD

**Issue by adamkdean** [edge/eslint-config-typescript#5]
I think we should disable `nonblock-statement-body-position`.

It's caused no end of frustration over the past few months, and while the idea that it stops people doing this...

```
if (condition)
  doSomethingOnlyIfCondition()
  thisWillHappenEitherWay()
```

...is valid, I don't think I've ever actually come across that. As it stands, there are if statements that are either so long that we have to disable the line length rule (to use beside) or we have to write more code just to satisfy multiple lines and a curly block.

I'm currently making use of `/* eslint-disable nonblock-statement-body-position */` but I sincerely believe this rule is causing more trouble than it is worth.

Is this something you could pick up and push out when you have a spare moment @annybs?

(p.s. labels on this repo! 😰 they're default)

**Comment by annybs** [comment]
This hasn't been re-raised since my last comment, so it doesn't seem like this proven to be a noticeable problem, particularly since we changed the `curly` rule.

I am about to create another discussion PR that if approved may further mitigate the issue - watch this (or I suppose rather, _that_) space.
